apiVersion: apps/v1
kind: Deployment
metadata:
  name: springbootcomments-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: springbootcomments-app
  template:
    metadata:
      labels:
        app: springbootcomments-app
    spec:
      containers:
        - name: springbootcomments-app
          image: 294104ust/docker_example_img:latest
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"
---
apiVersion: v1
kind: Service
metadata:
  name: springbootcomments-app-service
spec:
  selector:
    app: springbootcomments-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
